# generated by datamodel-codegen:
#   filename:  tele_tasmota_CEE97F_SENSOR.txt
#   timestamp: 2024-05-20T13:01:15+00:00

from __future__ import annotations

from pydantic import BaseModel


class ENERGY(BaseModel):
    TotalStartTime: str
    Total: float
    Yesterday: int
    Today: int
    Period: int
    Power: int
    ApparentPower: int
    ReactivePower: int
    Factor: int
    Voltage: int
    Current: int


class DeviceTelemetry(BaseModel):
    Time: str
    ENERGY: ENERGY
