# generated by datamodel-codegen:
#   filename:  tele_tasmota_CE1412_STATE.txt
#   timestamp: 2024-05-20T12:58:29+00:00

from __future__ import annotations

from pydantic import BaseModel


class Wifi(BaseModel):
    AP: int
    SSId: str
    BSSId: str
    Channel: int
    Mode: str
    RSSI: int
    Signal: int
    LinkCount: int
    Downtime: str


class DeviceState(BaseModel):
    Time: str
    Uptime: str
    UptimeSec: int
    Heap: int
    SleepMode: str
    Sleep: int
    LoadAvg: int
    MqttCount: int
    POWER: str
    Wifi: Wifi
