# generated by datamodel-codegen:
#   filename:  tasmota_discovery_C44F33D288A1_config.txt
#   timestamp: 2024-05-20T12:53:19+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class So(BaseModel):
    field_4: int = Field(..., alias="4")
    field_11: int = Field(..., alias="11")
    field_13: int = Field(..., alias="13")
    field_17: int = Field(..., alias="17")
    field_20: int = Field(..., alias="20")
    field_30: int = Field(..., alias="30")
    field_68: int = Field(..., alias="68")
    field_73: int = Field(..., alias="73")
    field_82: int = Field(..., alias="82")
    field_114: int = Field(..., alias="114")
    field_117: int = Field(..., alias="117")


class MQTTDiscovery(BaseModel):
    ip: str
    dn: str
    fn: List[Optional[str]]
    hn: str
    mac: str
    md: str
    ty: int
    if_: int = Field(..., alias="if")
    ofln: str
    onln: str
    state: List[str]
    sw: str
    t: str
    ft: str
    tp: List[str]
    rl: List[int]
    swc: List[int]
    swn: List[None]
    btn: List[int]
    so: So
    lk: int
    lt_st: int
    bat: int
    dslp: int
    sho: List
    sht: List
    ver: int
